# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Business Cooperative
tagline:          '<a href="https://instagram.com/leannewebbernet" target="_blank">@leannewebbernet</a>'
description:      '<a by href="http://instagram.com/leanne_webbernet" target="_blank"> Leanne Webber</a>'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Leanne Webber'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
